const Colors = {
	primaryL1: '#918EF5',
	primaryL2: '#A5A9F8',
	primaryL1_50: 'rgba(145, 142, 245, 0.50)',
	primaryL1_25: 'rgba(145, 142, 245, 0.25)',
	primaryL3: '#CDC9FD',

	secondary: '#F59569',

	green: '#B7F03C',
	blue: '#2394D3',
	red: '#fe3960',

	gradient1: 'linear-gradient(73.73deg, #5B4FEC -7.26%, #DFA891 100.28%)',

	gray: '#8D95A3',

	grayD1: '#747B87',
	grayD2: '#5D6168',
	grayD3: '#3D3D3D',

	grayL1: '#B0B9C8',
	grayL2: '#C6CFDF',
	grayL3: '#DFE6F3',
	grayL1_50: 'rgba(176, 185, 200, 0.25);',

	black: '#24242E',
	white: '#FFFFFF',
	white_50: 'rgba(255, 255, 255, 0.5)',

	Alice: {
		primaryMain: '#5158F6',
	},
	Pion: {
		primaryMain: '#4D3E9E',
	},
	Muon: {
		primaryMain: '#4D3E9E',
	},
}

export const palette = {
	Alice: {
		...Colors,
		...Colors.Alice,

		bg: '#EFF0F5',
		cardBg: '#FFFFFF',
		cardBg60: 'rgba(255, 255, 255, 0.6)',
		text: Colors.black,
		label: Colors.grayD1,
		input: Colors.grayL3,
		rowHover: Colors.grayL3,
		statValue: Colors.Alice.primaryMain,
		homeInputBg: Colors.white,
		homeInputStroke: Colors.primaryL1,
		homeInputIcon: Colors.Alice.primaryMain,
		graphStroke: Colors.Alice.primaryMain,
		dateRangeBg: Colors.white_50,
		button: Colors.Alice.primaryMain,
		appTabBg: Colors.grayL1_50,
		appTabActive: Colors.Alice.primaryMain,
		inputNameBg: Colors.grayL2,
		tabBg: Colors.grayL3,
		primaryText: Colors.Alice.primaryMain,
		uptime: Colors.blue,
	},
	Pion: {
		...Colors,
		...Colors.Pion,

		bg: '#252528',
		cardBg: '#3D3D3D',
		cardBg60: 'rgba(61, 61, 61, 0.6)',
		text: Colors.white,
		label: Colors.grayL1,
		input: Colors.grayD2,
		rowHover: Colors.grayD2,
		statValue: Colors.primaryL3,
		homeInputBg: Colors.grayD2,
		homeInputStroke: Colors.primaryL3,
		homeInputIcon: Colors.primaryL1,
		graphStroke: Colors.primaryL3,
		dateRangeBg: Colors.grayD2,
		button: Colors.primaryL1,
		appTabBg: Colors.grayD2,
		appTabActive: Colors.white,
		inputNameBg: Colors.grayD1,
		tabBg: Colors.grayD2,
		primaryText: Colors.primaryL1,
		uptime: Colors.green,
	},
	Muon: {
		...Colors,
		...Colors.Muon,

		bg: '#252528',
		cardBg: '#3D3D3D',
		cardBg60: 'rgba(61, 61, 61, 0.6)',
		text: Colors.white,
		label: Colors.grayL1,
		input: Colors.grayD2,
		rowHover: Colors.grayD2,
		statValue: Colors.primaryL3,
		homeInputBg: Colors.grayD2,
		homeInputStroke: Colors.primaryL3,
		homeInputIcon: Colors.primaryL1,
		graphStroke: Colors.primaryL3,
		dateRangeBg: Colors.grayD2,
		button: Colors.primaryL1,
		appTabBg: Colors.grayD2,
		appTabActive: Colors.white,
		inputNameBg: Colors.grayD1,
		tabBg: Colors.grayD2,
		primaryText: Colors.primaryL1,
		uptime: Colors.green,
	},
}
